# Generated by Django 5.2.9 on 2026-01-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('audit_year', models.IntegerField(blank=True, help_text='Year for the audit', null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Fieldwork', 'Fieldwork'), ('Archived', 'Archived')], default='Planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_engagements', to=settings.AUTH_USER_MODEL)),
                ('standards', models.ManyToManyField(help_text='Selected audit standards (e.g., ISO 27001, SOC 2)', related_name='engagements', to='audit.standard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(help_text='Control ID (e.g., A.5.1)', max_length=100)),
                ('control_name', models.CharField(blank=True, help_text='Control name/title', max_length=200)),
                ('control_description', models.TextField(help_text='Control description')),
                ('source', models.CharField(choices=[('auto', 'Auto-Generated from Standard'), ('manual', 'Manual/Custom'), ('questionnaire', 'Generated from Questionnaire')], default='auto', max_length=20)),
                ('test_applied', models.CharField(blank=True, help_text='Auditor-planned test method (empty by default, fully editable)', max_length=200, verbose_name='Test Applied')),
                ('test_performed', models.TextField(blank=True, help_text='Auditor execution notes – free text (empty by default, fully editable)', verbose_name='Test Performed')),
                ('test_results', models.TextField(blank=True, help_text="Audit conclusion – free text (e.g., 'No exceptions noted')", verbose_name='Test Results')),
                ('preparer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_signed_at', models.DateTimeField(blank=True, null=True)),
                ('testing_procedure', models.TextField(blank=True, help_text='Deprecated - use test_applied', verbose_name='Test Identified')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from Forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_admin_signed', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='audit.engagement')),
                ('preparer_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewer_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement Control',
                'verbose_name_plural': 'Engagement Controls',
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Questionnaire name', max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='audit.engagement')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='audit.standard')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('engagement', 'standard', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=250)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('READY_FOR_REVIEW', 'Ready for Review'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('auditor_test_notes', models.TextField(blank=True, verbose_name='Test Performed')),
                ('test_results', models.TextField(blank=True, verbose_name='Test Results')),
                ('preparer_signed', models.BooleanField(default=False)),
                ('preparer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_signed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('linked_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='audit.engagementcontrol')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['linked_control__control_id'],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='request_docs/%Y/%m/%d/')),
                ('doc_type', models.CharField(choices=[('evidence', 'Evidence'), ('workpaper', 'Workpaper')], default='workpaper', max_length=20)),
                ('folder', models.CharField(choices=[('project_admin', '01. Project Admin'), ('report_templates', 'Report Templates'), ('reports', 'Reports'), ('workplan', 'Workplan'), ('evidence', 'Evidence'), ('screenshots', 'Screenshots'), ('policies', 'Policies'), ('logs', 'Logs'), ('other', 'Other')], default='workplan', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.engagement')),
                ('linked_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='audit.engagementcontrol')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.request')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.standard')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StandardControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(help_text='Control identifier (e.g., A.5.1)', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Control title', max_length=500)),
                ('control_description', models.TextField(help_text='Detailed control description')),
                ('domain', models.CharField(blank=True, help_text='Control domain (e.g., Organizational Controls)', max_length=200)),
                ('standard_reference', models.CharField(blank=True, max_length=200)),
                ('default_testing_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='audit.standard')),
            ],
            options={
                'ordering': ['standard__name', 'control_id'],
                'unique_together': {('standard', 'control_id')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question text (defaults to control description)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='audit.questionnaire')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questions', to='audit.standardcontrol')),
            ],
            options={
                'ordering': ['order', 'control__control_id'],
                'unique_together': {('questionnaire', 'control')},
            },
        ),
        migrations.AddField(
            model_name='engagementcontrol',
            name='standard_control',
            field=models.ForeignKey(blank=True, help_text='Source control from Standard Library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_controls', to='audit.standardcontrol'),
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'N/A')], max_length=10, null=True)),
                ('response_text', models.TextField(blank=True, help_text='Optional comment/notes')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audit.questionnairequestion')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audit.questionnaire')),
            ],
            options={
                'ordering': ['question__order'],
                'unique_together': {('questionnaire', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_response_sets', to='audit.engagement')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_response_sets', to='audit.standard')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('engagement', 'standard')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='engagementcontrol',
            unique_together={('engagement', 'control_id')},
        ),
    ]
