# Generated by Django 5.2.9 on 2026-01-05 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Fieldwork', 'Fieldwork'), ('Archived', 'Archived')], default='Planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('testing_procedure', models.TextField(verbose_name='Test Identified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='audit.engagement')),
            ],
            options={
                'ordering': ['control_id'],
                'unique_together': {('engagement', 'control_id')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In-Review', 'In-Review'), ('Accepted', 'Accepted'), ('Returned', 'Returned')], default='Open', max_length=20)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/', verbose_name='Evidence')),
                ('workpaper_file', models.FileField(blank=True, null=True, upload_to='workpapers/%Y/%m/%d/', verbose_name='Workpaper')),
                ('auditor_test_notes', models.TextField(blank=True, verbose_name='Test Performed')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('linked_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='audit.controlrequirement')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['linked_control__control_id'],
            },
        ),
    ]
