# Generated by Django 5.2.9 on 2026-01-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlrequirement',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year for the control (1985-2050)', null=True),
        ),
    ]
