# Generated by Django 5.0.6 on 2026-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcontrol',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto-Generated from Standard'), ('manual', 'Manual/Custom'), ('questionnaire', 'Generated from Questionnaire'), ('excel', 'Generated from Excel Upload')], default='auto', max_length=20),
        ),
    ]
