# Generated by Django 5.0.6 on 2026-02-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_engagementcontrol_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcontrol',
            name='evidence_required',
            field=models.TextField(blank=True, help_text='Describe what evidence the client must provide (e.g. policy document, screenshots, logs, approvals)', verbose_name='Evidence Required'),
        ),
        migrations.AlterField(
            model_name='engagementcontrol',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto-Generated from Standard'), ('manual', 'Manual/Custom'), ('questionnaire', 'Generated from Questionnaire')], default='auto', max_length=20),
        ),
    ]
