# Generated by Django 5.0.6 on 2026-02-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_engagementcontrol_source'),
        ('audit', '0002_seed_iso27001_annex_a_controls'),
    ]

    operations = [
    ]
