# Generated by Django 5.2.9 on 2026-01-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_requestdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='request',
            name='evidence_file',
        ),
        migrations.RemoveField(
            model_name='request',
            name='workpaper_file',
        ),
        migrations.AddField(
            model_name='controlrequirement',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto-Generated'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='engagement',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='audit.standard'),
        ),
        migrations.CreateModel(
            name='StandardControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=100)),
                ('control_description', models.TextField()),
                ('standard_reference', models.CharField(blank=True, max_length=200)),
                ('default_testing_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='audit.standard')),
            ],
            options={
                'ordering': ['standard__name', 'control_id'],
                'unique_together': {('standard', 'control_id')},
            },
        ),
        migrations.AddField(
            model_name='controlrequirement',
            name='standard_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_controls', to='audit.standardcontrol'),
        ),
    ]
