# Generated by Django 5.2.9 on 2026-01-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_controlrequirement_metadata_request_test_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=250),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='folder',
            field=models.CharField(choices=[('project_admin', '01. Project Admin'), ('report_templates', 'Report Templates'), ('reports', 'Reports'), ('workplan', 'Workplan'), ('other', 'Other')], default='workplan', max_length=30),
        ),
    ]
