# Generated by Django 5.2.9 on 2026-01-07 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_request_description_request_due_date_request_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='standard',
        ),
        migrations.AddField(
            model_name='engagement',
            name='audit_year',
            field=models.IntegerField(blank=True, help_text='Year for the audit', null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='engagement',
            name='standards',
            field=models.ManyToManyField(help_text='Selected audit standards (e.g., ISO 27001, SOC 2)', related_name='engagements', to='audit.standard'),
        ),
        migrations.CreateModel(
            name='EngagementControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(help_text='Control ID (e.g., A.5.1)', max_length=100)),
                ('control_name', models.CharField(blank=True, help_text='Control name/title', max_length=200)),
                ('control_description', models.TextField(help_text='Control description')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In-Review', 'In-Review'), ('Accepted', 'Accepted'), ('Returned', 'Returned')], default='Open', max_length=20)),
                ('source', models.CharField(choices=[('auto', 'Auto-Generated from Standard'), ('manual', 'Manual/Custom')], default='auto', max_length=10)),
                ('testing_procedure', models.TextField(blank=True, verbose_name='Test Identified')),
                ('test_results', models.TextField(blank=True, verbose_name='Test Results')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from Forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='audit.engagement')),
                ('standard_control', models.ForeignKey(blank=True, help_text='Source control from Standard Library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_controls', to='audit.standardcontrol')),
            ],
            options={
                'verbose_name': 'Engagement Control',
                'verbose_name_plural': 'Engagement Controls',
                'ordering': ['control_id'],
                'unique_together': {('engagement', 'control_id')},
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='linked_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='audit.engagementcontrol'),
        ),
        migrations.DeleteModel(
            name='ControlRequirement',
        ),
    ]
