# Generated by Django 5.2.9 on 2026-01-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_remove_engagement_standard_engagement_audit_year_and_more'),
    ]

    operations = [
    ]
