# Generated by Django 5.2.9 on 2026-01-07 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_migrate_control_requirement_to_engagement_control'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestdocument',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.engagement'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='linked_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='audit.engagementcontrol'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='doc_type',
            field=models.CharField(choices=[('evidence', 'Evidence'), ('workpaper', 'Workpaper'), ('report', 'Report'), ('admin', 'Admin'), ('template', 'Template')], default='workpaper', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.request'),
        ),
    ]
