# Generated by Django 5.2.9 on 2026-01-07 08:45

from django.db import migrations


def backfill_engagements(apps, schema_editor):
    """
    Backfill engagement field for existing RequestDocument records.
    """
    RequestDocument = apps.get_model('audit', 'RequestDocument')
    
    for doc in RequestDocument.objects.filter(engagement__isnull=True):
        if doc.request and doc.request.linked_control:
            doc.engagement = doc.request.linked_control.engagement
            doc.save(update_fields=['engagement'])


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - no action needed.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_make_requestdocument_flexible'),
    ]

    operations = [
        migrations.RunPython(backfill_engagements, reverse_backfill),
    ]
