# Generated by Django 5.2.9 on 2026-01-07 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_backfill_document_engagements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponseset',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_response_sets', to='audit.engagement'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponseset',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_response_sets', to='audit.standard'),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Questionnaire name', max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='audit.engagement')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='audit.standard')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('engagement', 'standard', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question text (defaults to control description)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questions', to='audit.standardcontrol')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='audit.questionnaire')),
            ],
            options={
                'ordering': ['order', 'control__control_id'],
                'unique_together': {('questionnaire', 'control')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'N/A')], max_length=10, null=True)),
                ('response_text', models.TextField(blank=True, help_text='Optional comment/notes')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audit.questionnairequestion')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audit.questionnaire')),
            ],
            options={
                'ordering': ['question__order'],
                'unique_together': {('questionnaire', 'question')},
            },
        ),
    ]
