# Generated by Django 5.2.9 on 2026-01-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_add_questionnaire_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcontrol',
            name='test_performed',
            field=models.TextField(blank=True, help_text='Test performed notes from questionnaires or manual entry', verbose_name='Test Performed / Auditor Notes'),
        ),
        migrations.AlterField(
            model_name='engagementcontrol',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto-Generated from Standard'), ('manual', 'Manual/Custom'), ('questionnaire', 'Generated from Questionnaire')], default='auto', max_length=20),
        ),
    ]
