# Generated by Django 5.2.9 on 2026-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_add_questionnaire_source_and_test_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcontrol',
            name='test_applied',
            field=models.CharField(blank=True, choices=[('Inquiry', 'Inquiry'), ('Inspection', 'Inspection'), ('Observation', 'Observation'), ('Reperformance', 'Reperformance')], help_text='Auditor-planned test method', max_length=20, verbose_name='Test Applied'),
        ),
        migrations.AlterField(
            model_name='engagementcontrol',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Complete', 'Complete')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='engagementcontrol',
            name='test_performed',
            field=models.TextField(blank=True, help_text='Auditor execution notes – free text', verbose_name='Test Performed'),
        ),
        migrations.AlterField(
            model_name='engagementcontrol',
            name='test_results',
            field=models.CharField(blank=True, choices=[('No exceptions noted', 'No exceptions noted'), ('Exceptions identified', 'Exceptions identified')], help_text='Audit conclusion', max_length=50, verbose_name='Test Results'),
        ),
        migrations.AlterField(
            model_name='engagementcontrol',
            name='testing_procedure',
            field=models.TextField(blank=True, help_text='Deprecated - use test_applied', verbose_name='Test Identified'),
        ),
    ]
