# Generated by Django 5.2.9 on 2026-01-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_change_test_results_to_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementcontrol',
            name='status',
        ),
        migrations.AddField(
            model_name='engagementcontrol',
            name='admin_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementcontrol',
            name='admin_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_admin_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementcontrol',
            name='preparer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementcontrol',
            name='preparer_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_prepared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementcontrol',
            name='reviewer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementcontrol',
            name='reviewer_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
