# Generated by Django 5.2.9 on 2026-01-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_remove_status_add_signoffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcontrol',
            name='test_applied',
            field=models.CharField(blank=True, help_text='Auditor-planned test method (empty by default, fully editable)', max_length=200, verbose_name='Test Applied'),
        ),
    ]
