# Generated by Django 5.2.9 on 2026-01-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_remove_test_applied_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardcontrol',
            name='domain',
            field=models.CharField(blank=True, help_text='Control domain (e.g., Organizational Controls)', max_length=200),
        ),
        migrations.AddField(
            model_name='standardcontrol',
            name='title',
            field=models.CharField(blank=True, help_text='Control title', max_length=500),
        ),
        migrations.AlterField(
            model_name='standardcontrol',
            name='control_description',
            field=models.TextField(help_text='Detailed control description'),
        ),
        migrations.AlterField(
            model_name='standardcontrol',
            name='control_id',
            field=models.CharField(help_text='Control identifier (e.g., A.5.1)', max_length=100),
        ),
    ]
