# Generated by Django 5.2.9 on 2026-01-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_load_iso27001_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdocument',
            name='folder',
            field=models.CharField(choices=[('project_admin', '01. Project Admin'), ('report_templates', 'Report Templates'), ('reports', 'Reports'), ('workplan', 'Workplan'), ('evidence', 'Evidence'), ('screenshots', 'Screenshots'), ('policies', 'Policies'), ('logs', 'Logs'), ('other', 'Other')], default='workplan', max_length=30),
        ),
    ]
