# Generated by Django 5.2.9 on 2026-01-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_add_evidence_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('READY_FOR_REVIEW', 'Ready for Review'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
    ]
