# Generated by Django 5.2.9 on 2026-01-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0021_update_request_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='preparer_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='preparer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='reviewer_signed',
            field=models.BooleanField(default=False),
        ),
    ]
